"""create otp table

Revision ID: 843f9c4717ea
Revises: fc41a1432d44
Create Date: 2026-08-14 15:33:58.018221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "843f9c4717ea"
down_revision: Union[str, None] = "fc41a1432d44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "otps",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("otp", sa.String(length=10), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_otp_email_expires", "otps", ["email", "expires_at"], unique=False
    )
    op.create_index(op.f("ix_otps_email"), "otps", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_otps_email"), table_name="otps")
    op.drop_index("idx_otp_email_expires", table_name="otps")
    op.drop_table("otps")
    # ### end Alembic commands ###
