"""initial

Revision ID: 9646a69f6274
Revises: a9dcb8c9fa77
Create Date: 2026-07-29 09:37:31.239676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9646a69f6274"
down_revision: Union[str, None] = "a9dcb8c9fa77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cart_items", sa.Column("product_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        None, "cart_items", "products", ["product_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("wishlist_items", sa.Column("product_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        None, "wishlist_items", "products", ["product_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "wishlist_items", type_="foreignkey")
    op.drop_column("wishlist_items", "product_id")
    op.drop_constraint(None, "cart_items", type_="foreignkey")
    op.drop_column("cart_items", "product_id")
    # ### end Alembic commands ###
